### ISSUE TITLE
Lottery Ticket Generation

### ISSUE THREAD

**Issue by jdimodugno** [pancakeswap/lottery-contract#10]
After buying some tickets, I've noticed that one number of a ticket was repeated.
After checking this file: [Lottery.sol](https://github.com/pancakeswap/lottery-contract/blob/5dcea3af5f0fa7eaceded7be3b969330bc89f254/contracts/Lottery.sol#L211)

1. Shouldn't the Buy method check and avoid repeated items on the ticket?
2. Shouldn't the Buy method be called inside MultiBuy?

![image](https://user-images.githubusercontent.com/16907390/109985299-5fb43c80-7ce3-11eb-8a44-884736cf4193.png)

Thanks.

**Comment by ArtemKolichenkov** [comment]
1. Why would there be logic to avoid repeated numbers? Tickets can have repeated numbers just like the winning combination can have it. You can get a ticket with numbers `[5,5,5,5]` and then with 4-match if winning numbers are `[5,5,5,5]`
2. There is duplication in the code yes, that would be good to refactor, BUT - PR #5 touches `multiBuy` a bit now to support batch minting. So once it lands `buy` and `multiBuy` will be quite different 🙂
